### ISSUE TITLE
[🎉FEATURE] 보드페이지 작성

### ISSUE THREAD

**Issue by Ryujeonggeun** [b-14-team/main_repo#50]
## 💬 설명
핵심 기능 위주로 만들어보겠습니다.

## ☑️TO-DO
- [ ] 버튼으로 카드 작성하기
- [ ] 버튼으로 칼럼 추가하기
- [ ] 드래그로 카드 움직이기
